### PR TITLE
fix up <input class="map_value"> (fixes #121)

### LINKED ISSUE #121: <input class="map_value"> should also have `string` in `class`
image
image

Notice the blue border highlights for `<input class="text">` only.

### PR DESCRIPTION
**Pull request by cvan**
### before

screen shot 2016-07-07 at 2 01 36 am
### after (after #119 and #126 are merged)

screen shot 2016-07-07 at 1 57 39 am

### CODE REVIEW

File: src/components/widgets/TextureWidget.js [hunk 1]
```diff
@@ -178,7 +178,7 @@ export default class TextureWidget extends React.Component {
       <span className="texture">
         <span className={this.state.valueType}></span>
         <canvas ref="canvas" width="32" height="16" title={this.props.mapName} onClick={this.openDialog}></canvas>
-        <input className="map_value" type="text" value={this.state.value} onChange={this.onChange}/>
+        <input className="map_value string" type="text" value={this.state.value} onChange={this.onChange}/>
```
Comment (cvan) [inline src/components/widgets/TextureWidget.js:181]: the underscore is inconsistent with other class names in this project. what shall I change it to?

**Comment by fernandojsg** [comment]
Perfect, thank you!
