### PR TITLE
Fixes #391 - Inspector panel doesnt works if registry build fails

### LINKED ISSUE #391: If the registry build fails to fetch, Inspector component panel doesn't work
INSPECTOR.componentLoader.components is null, and Object.keys fails.

### PR DESCRIPTION
**Pull request by fernandojsg**

### CODE REVIEW

File: src/lib/componentloader.js [hunk 1]
```diff
@@ -22,8 +22,12 @@ ComponentLoader.prototype = {
     xhr.open('GET', registryBaseUrl + getMajorVersion(AFRAME.version) + '.json');
 
     xhr.onload = () => {
-      this.components = JSON.parse(xhr.responseText).components;
-      console.info('Components in registry:', Object.keys(this.components).length);
+      if (xhr.status === 404) {
+        console.error('Error loading registry file: 404');
+      } else {
+        this.components = JSON.parse(xhr.responseText).components;
+        console.info('Components in registry:', Object.keys(this.components).length);
```
Comment (dmarcos) [inline src/lib/componentloader.js]: Do we want a better message here? The error message shows what happened but success does not.
"Registry file loaded. " + Object.keys(this.components).length + " components available"

**Comment by dmarcos** [comment]
Just made a small comment on the success message. It looks good to me.

File: src/lib/componentloader.js (hunk 1 above)
Comment (fernandojsg) [reply src/lib/componentloader.js]: Thanks, modified!
