### PR TITLE
Added keyboard navigation on scenegraph and fixed persistence of the selected value

### LINKED ISSUE #7: Enable keyboard navigation to cycle through the scenegraph list
to make things easy, you could have a radio form field for each item

### PR DESCRIPTION
**Pull request by fernandojsg**
Fixed #7 to enable navigation with up/down arrow, and #49 to persist the selected entity after reentering editor

### CODE REVIEW

File: app/components/Scenegraph.js [hunk 1]
```diff
@@ -93,17 +87,66 @@ var Scenegraph = React.createClass({
...
 
-    return <div className="Outliner" tabIndex="0" id="outliner">
+    document.addEventListener('componentremoved', function(e){
+      this.forceUpdate();
+    }.bind(this));
+    Events.on('entitySelected', function(entity, self) {
+      if (self) return;
+      this.setValue(entity);
+    }.bind(this));
+    Events.on('entityIdChanged', function(e) {
```
Comment (cvan) [inline app/components/Scenegraph.js:107]: `e` is unnecessary

File: app/components/Scenegraph.js [hunk 2]
```diff
@@ -93,17 +87,66 @@ var Scenegraph = React.createClass({
...
+    this.setState({options: options});
+  },
+  componentDidMount: function() {
+    this.rebuildOptions();
 
-    return <div className="Outliner" tabIndex="0" id="outliner">
+    document.addEventListener('componentremoved', function(e){
+      this.forceUpdate();
+    }.bind(this));
+    Events.on('entitySelected', function(entity, self) {
```
Comment (cvan) [inline app/components/Scenegraph.js:103]: `e` or `entity`?
